// General Settings
const CANVAS = {
    WIDTH : 600,
    HEIGHT: 600,
    BACKGROUND_COLOR : 'white'
}

CANVAS.MARGINS_RATIO = {
    LEFT : 0.0,
    RIGHT : 0.0,
    TOP : 0.0,
    BOTTOM : 0.0
}

CANVAS.MARGINS = {
    LEFT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.LEFT,
    RIGHT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.RIGHT,
    TOP : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.TOP,
    BOTTOM : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.BOTTOM
}

CANVAS.MARGINS_POSITION = {
    LEFT: CANVAS.MARGINS.LEFT,
    RIGHT: CANVAS.WIDTH - CANVAS.MARGINS.RIGHT,
    TOP: CANVAS.MARGINS.TOP,
    BOTTOM: CANVAS.HEIGHT - CANVAS.MARGINS.BOTTOM
}

const BACKGROUND_COLOR = "white"
const DEBUG_COLOR = "magenta"
