// General Settings
const CANVAS = {
    WIDTH : 750,
    HEIGHT: 750,
    BACKGROUND_COLOR : 'white'
}

CANVAS.MARGINS_RATIO = {
    LEFT : 0.02,
    RIGHT : 0.02,
    TOP : 0.02,
    BOTTOM : 0.02
}

CANVAS.MARGINS = {
    LEFT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.LEFT,
    RIGHT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.RIGHT,
    TOP : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.TOP,
    BOTTOM : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.BOTTOM
}

CANVAS.MARGINS_POSITION = {
    LEFT: CANVAS.MARGINS.LEFT,
    RIGHT: CANVAS.WIDTH - CANVAS.MARGINS.RIGHT,
    TOP: CANVAS.MARGINS.TOP,
    BOTTOM: CANVAS.HEIGHT - CANVAS.MARGINS.BOTTOM
}

const BACKGROUND_COLOR = "white"
const DEBUG_COLOR = "magenta"

// Project Settings
const N_SQUARES_V = 6
const N_SQUARES_H = 6

const PAD_RATIO = 0.4

const SQUARE_STEP = (CANVAS.WIDTH - CANVAS.MARGINS.LEFT - CANVAS.MARGINS.RIGHT)/N_SQUARES_H
const SQUARE_SIZE = (CANVAS.WIDTH - CANVAS.MARGINS.LEFT - CANVAS.MARGINS.RIGHT)/(N_SQUARES_H + ((N_SQUARES_H) * PAD_RATIO))
